import type { Order } from './types';

export const orders: Order[] = [
  {
    id: 'order-1',
    type: 'BUY',
    ticker: 'YESBANK.NS',
    quantity: 1000,
    filledQuantity: 0,
    limitPrice: 24.50,
    status: 'Pending',
    timestamp: '5 mins ago',
    exchange: 'NSE',
    orderType: 'CNC LIMIT',
    ltp: 24.55,
  },
  {
    id: 'order-2',
    type: 'BUY',
    ticker: 'RELIANCE.NS',
    quantity: 20,
    filledQuantity: 0,
    limitPrice: 2950.00,
    status: 'Pending',
    timestamp: '22 mins ago',
    exchange: 'NSE',
    orderType: 'CNC LIMIT',
    ltp: 2955.40,
  },
    {
    id: 'order-3',
    type: 'SELL',
    ticker: 'TCS.NS',
    quantity: 10,
    filledQuantity: 10,
    limitPrice: 3850.00,
    status: 'Executed',
    timestamp: '1 day ago',
    exchange: 'NSE',
    orderType: 'CNC LIMIT',
    ltp: 3850.00,
  },
];
