-- Create the messages table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.messages (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NULL,
  user_name text NULL,
  content text NULL,
  CONSTRAINT messages_pkey PRIMARY KEY (id)
);

-- Enable Row Level Security for the messages table
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Drop existing policies for messages to avoid conflicts, then recreate them
DROP POLICY IF EXISTS "Allow authenticated users to view messages" ON public.messages;
CREATE POLICY "Allow authenticated users to view messages"
ON public.messages
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Allow authenticated users to insert their own messages" ON public.messages;
CREATE POLICY "Allow authenticated users to insert their own messages"
ON public.messages
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);


-- Create the watchlists table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.watchlists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  market text NOT NULL,
  name text NOT NULL,
  stock_tickers text[] NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT unique_watchlist_name_per_user_market UNIQUE (user_id, market, name)
);

-- Enable RLS and define policies for watchlists
ALTER TABLE public.watchlists ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view their own watchlists" ON public.watchlists;
CREATE POLICY "Users can view their own watchlists" ON public.watchlists FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert their own watchlists" ON public.watchlists;
CREATE POLICY "Users can insert their own watchlists" ON public.watchlists FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update their own watchlists" ON public.watchlists;
CREATE POLICY "Users can update their own watchlists" ON public.watchlists FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can delete their own watchlists" ON public.watchlists;
CREATE POLICY "Users can delete their own watchlists" ON public.watchlists FOR DELETE USING (auth.uid() = user_id);


-- Create the orders table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.orders (
    id text PRIMARY KEY,
    user_id uuid NOT NULL DEFAULT auth.uid(),
    market text NOT NULL,
    type text NOT NULL,
    ticker text NOT NULL,
    quantity integer NOT NULL,
    filled_quantity integer NOT NULL,
    limit_price numeric NOT NULL,
    trigger_price numeric,
    status text NOT NULL,
    timestamp text NOT NULL,
    exchange text NOT NULL,
    order_type text NOT NULL,
    ltp numeric NOT NULL,
    is_amo boolean,
    product text,
    order_method text,
    is_short_sell boolean,
    is_exit boolean,
    is_adding boolean,
    executed_at timestamp with time zone,
    realized_pnl numeric,
    stop_loss_value numeric,
    target_value numeric
);

-- Enable RLS and define policies for orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage their own orders" ON public.orders;
CREATE POLICY "Users can manage their own orders" ON public.orders FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);


-- Create the funds table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.funds (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL DEFAULT auth.uid(),
  market text NOT NULL,
  balance numeric NOT NULL,
  can_add_more boolean DEFAULT true,
  last_profit_check numeric DEFAULT 0,
  CONSTRAINT unique_fund_per_user_market UNIQUE (user_id, market)
);

-- Enable RLS and define policies for funds
ALTER TABLE public.funds ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage their own funds" ON public.funds;
CREATE POLICY "Users can manage their own funds" ON public.funds FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
