-- Create the messages table
CREATE TABLE public.messages (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NULL,
  user_name text NULL,
  content text NULL,
  CONSTRAINT messages_pkey PRIMARY KEY (id)
);

-- Enable Row Level Security (RLS) for the messages table
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows authenticated users to insert their own messages
CREATE POLICY "Enable insert for authenticated users only"
ON public.messages
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Create a policy that allows all users (authenticated or not) to read all messages
CREATE POLICY "Enable read access for all users"
ON public.messages
FOR SELECT
TO public
USING (true);

-- Set up Supabase real-time for the messages table
-- 1. Go to Database > Replication in your Supabase dashboard
-- 2. Find the "Source" for `public` schema and click the "0 tables" link.
-- 3. Toggle on the `messages` table and click "Save".
