-- Create the messages table
CREATE TABLE public.messages (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NULL,
  user_name text NULL,
  content text NULL,
  CONSTRAINT messages_pkey PRIMARY KEY (id)
);

-- Create the watchlists table
CREATE TABLE public.watchlists (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    market text NOT NULL,
    name text NOT NULL,
    stock_tickers text[] NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT watchlists_pkey PRIMARY KEY (id)
);

-- Create the orders table
CREATE TABLE public.orders (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    market text NOT NULL,
    order_data jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

-- Create the funds table
CREATE TABLE public.funds (
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    market text NOT NULL,
    balance numeric NOT NULL,
    can_add_more boolean NOT NULL DEFAULT true,
    last_profit_check numeric NOT NULL DEFAULT 0,
    CONSTRAINT funds_pkey PRIMARY KEY (user_id, market)
);

-- Enable Row Level Security for all tables
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.watchlists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.funds ENABLE ROW LEVEL SECURITY;

-- Create policies for messages table
CREATE POLICY "Allow authenticated users to view messages"
ON public.messages FOR SELECT TO authenticated USING (true);

CREATE POLICY "Allow authenticated users to insert their own messages"
ON public.messages FOR INSERT TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Create policies for watchlists table
CREATE POLICY "Allow users to manage their own watchlists"
ON public.watchlists FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Create policies for orders table
CREATE POLICY "Allow users to manage their own orders"
ON public.orders FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Create policies for funds table
CREATE POLICY "Allow users to manage their own funds"
ON public.funds FOR ALL TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
